package View;

import Controller.*;
import Model.Cliente;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author isaacmgz
 */
public class GUIAddDelCliente extends javax.swing.JFrame {
    
    public GUIAddDelCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarListadoClientes();
    }
    
    private ILista<Cliente> repoClientes = new GestionClientes();
    private List<Cliente> listaClientes;
    
    private void cargarListadoClientes() {
        try {
            listaClientes = new GestionClientes().cargarTodos();
            jComboBoxClientes.removeAllItems();
            for (Cliente c : listaClientes) {
                jComboBoxClientes.addItem(c.getNombreCliente());
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Error cargando clientes: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
   
    private void limpiarCampos() {
        jTNombreCli.setText("");
        jTNITCli.setText("");
        jTEmailCli.setText("");
        jComboBoxClientes.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTNombreCli = new javax.swing.JTextField();
        jTNITCli = new javax.swing.JTextField();
        jTEmailCli = new javax.swing.JTextField();
        jToggleButtonAddCli = new javax.swing.JToggleButton();
        jToggleButtonDelCli = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jButtonActualizarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.hoverBorderColor"));
        jLabel1.setText("Administrar Clientes");

        jLabel2.setText("Cliente:");

        jLabel3.setText("NIT:");

        jLabel4.setText("Email:");

        jTNombreCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreCliActionPerformed(evt);
            }
        });

        jTNITCli.setText("CLI");

        jToggleButtonAddCli.setText("Agregar Cliente");
        jToggleButtonAddCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAddCliActionPerformed(evt);
            }
        });

        jToggleButtonDelCli.setText("Eliminar Cliente");
        jToggleButtonDelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDelCliActionPerformed(evt);
            }
        });

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientesActionPerformed(evt);
            }
        });

        jButtonActualizarCliente.setText("Actualizar Cliente");
        jButtonActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jToggleButtonAddCli)
                        .addGap(58, 58, 58)
                        .addComponent(jToggleButtonDelCli)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonActualizarCliente)
                        .addContainerGap(156, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTNombreCli, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jTNITCli)
                            .addComponent(jTEmailCli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(254, 254, 254))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTNITCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 107, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButtonAddCli)
                            .addComponent(jToggleButtonDelCli)
                            .addComponent(jButtonActualizarCliente))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUIEmpresa empresaWin = new GUIEmpresa();
        empresaWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTNombreCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreCliActionPerformed

    private void jToggleButtonDelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDelCliActionPerformed
        int sel = jComboBoxClientes.getSelectedIndex();
        if (sel < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente.");
            return;
        }
        Cliente c = listaClientes.get(sel);
        repoClientes.eliminar(c.getIdCliente());
        JOptionPane.showMessageDialog(this,
                "Cliente “" + c.getNombreCliente() + "” eliminado.");
        limpiarCampos();
        cargarListadoClientes();
    }//GEN-LAST:event_jToggleButtonDelCliActionPerformed

    private void jToggleButtonAddCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAddCliActionPerformed

        String nombre = jTNombreCli.getText().trim();
        String id = jTNITCli.getText().trim();
        String email = jTEmailCli.getText().trim();

        if (nombre.isEmpty() || id.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.");
            return;
        }
        if (repoClientes.obtener(id) != null) {
            JOptionPane.showMessageDialog(this,
                    "El NIT ya existe: " + id,
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cliente nuevo = new Cliente(nombre, id, email);
        repoClientes.agregar(nuevo);
        JOptionPane.showMessageDialog(this, "Cliente agregado con éxito.");
        limpiarCampos();
        cargarListadoClientes();
    }//GEN-LAST:event_jToggleButtonAddCliActionPerformed

    private void jComboBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientesActionPerformed
        int sel = jComboBoxClientes.getSelectedIndex();
        if (sel >= 0) {
            Cliente c = listaClientes.get(sel);
            jTNombreCli.setText(c.getNombreCliente());
            jTNITCli.setText(c.getIdCliente());
            jTEmailCli.setText(c.getEmailCliente());
        }
    }//GEN-LAST:event_jComboBoxClientesActionPerformed

    private void jButtonActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarClienteActionPerformed
        String nombre = jTNombreCli.getText().trim();
        String id = jTNITCli.getText().trim();
        String email = jTEmailCli.getText().trim();

        if (nombre.isEmpty() || id.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.");
            return;
        }
        Cliente existente = repoClientes.obtener(id);
        if (existente == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay cliente registrado con NIT " + id,
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        Cliente actualizado = new Cliente(nombre, id, email);
        ((GestionClientes) repoClientes).actualizarCliente(actualizado);
        JOptionPane.showMessageDialog(this,
                "Cliente actualizado con éxito.");
        limpiarCampos();
        cargarListadoClientes();
    }//GEN-LAST:event_jButtonActualizarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAddDelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAddDelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAddDelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAddDelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAddDelCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActualizarCliente;
    private javax.swing.JComboBox<String> jComboBoxClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTEmailCli;
    private javax.swing.JTextField jTNITCli;
    private javax.swing.JTextField jTNombreCli;
    private javax.swing.JToggleButton jToggleButtonAddCli;
    private javax.swing.JToggleButton jToggleButtonDelCli;
    // End of variables declaration//GEN-END:variables
}
