package View;

import Controller.*;
import Model.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author isaacmgz
 */
public class GUIGestionarFarmaco extends javax.swing.JFrame {

    /**
     * Creates new form GUIAgregarMedicamento
     */
    private ILista<Farmaco> repoFarmacos = new GestionFarmacos();
    private List<Farmaco> listaFarmacosGestion;

    public GUIGestionarFarmaco() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarListadoFarmacos();
    }

    private void cargarListadoFarmacos() {
        try {
            listaFarmacosGestion = repoFarmacos.cargarTodos();
            jComboBoxEliminarFarmaco.removeAllItems();
            for (Farmaco f : listaFarmacosGestion) {
                jComboBoxEliminarFarmaco.addItem(f.getNombre());
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "No se pudieron cargar los fármacos: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCamposYRefrescar() {
        jTNuevoFarmaco.setText("");
        jTIdNuevoFarmaco.setText("");
        jTPresentacionesNuevas.setText("");
        jTDosificacionesNuevas.setText("");
        jTUnidadNuevoFarmaco.setText("");
        cargarListadoFarmacos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTNuevoFarmaco = new javax.swing.JTextField();
        jTIdNuevoFarmaco = new javax.swing.JTextField();
        jTPresentacionesNuevas = new javax.swing.JTextField();
        jTDosificacionesNuevas = new javax.swing.JTextField();
        jTUnidadNuevoFarmaco = new javax.swing.JTextField();
        jButtonAgregarFarmaco = new javax.swing.JButton();
        jButtonEliminarFarmaco = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBoxEliminarFarmaco = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTPrecioUnidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.default.borderColor"));
        jLabel1.setText("Agregar Farmaco");

        jLabel2.setText("Nombre Farmaco:");

        jLabel3.setText("id Farmaco:");

        jLabel4.setText("Presentaciones (Separadas por comas):");

        jLabel5.setText("Dosificaciones (Separadas por comas):");

        jLabel6.setText("Unidad:");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel7.setForeground(javax.swing.UIManager.getDefaults().getColor("Component.error.focusedBorderColor"));
        jLabel7.setText("Eliminar Farmaco");

        jLabel8.setText("Farmaco Eliminar:");

        jButtonAgregarFarmaco.setText("Agregar Farmaco");
        jButtonAgregarFarmaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFarmacoActionPerformed(evt);
            }
        });

        jButtonEliminarFarmaco.setText("Eliminar Farmaco");
        jButtonEliminarFarmaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarFarmacoActionPerformed(evt);
            }
        });

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxEliminarFarmaco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEliminarFarmaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEliminarFarmacoActionPerformed(evt);
            }
        });

        jLabel9.setText("Precio unidad:");

        jTPrecioUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrecioUnidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTDosificacionesNuevas, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jTPresentacionesNuevas)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTUnidadNuevoFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTNuevoFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTIdNuevoFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(237, 237, 237))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonEliminarFarmaco)
                            .addGap(167, 167, 167)
                            .addComponent(jButton1)
                            .addGap(17, 17, 17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonAgregarFarmaco)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxEliminarFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(52, 52, 52)))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNuevoFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTIdNuevoFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTPresentacionesNuevas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTDosificacionesNuevas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTUnidadNuevoFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregarFarmaco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxEliminarFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEliminarFarmaco)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUIEmpresa empresaWin = new GUIEmpresa();
        empresaWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAgregarFarmacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFarmacoActionPerformed
        try {
    // --------  Validaciones básicas. ------------
    String nombre = jTNuevoFarmaco.getText().trim();
    String idText = jTIdNuevoFarmaco.getText().trim();
    String unidad = jTUnidadNuevoFarmaco.getText().trim();
    String presText = jTPresentacionesNuevas.getText().trim();
    String dosisText = jTDosificacionesNuevas.getText().trim();
    String precioText = jTPrecioUnidad.getText().trim(); 

    if (nombre.isEmpty() || idText.isEmpty() 
        || unidad.isEmpty() || presText.isEmpty() 
        || dosisText.isEmpty() || precioText.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Completa todos los campos.");
      return;
    }

    int id = Integer.parseInt(idText);
    double precio = Double.parseDouble(precioText);

    // ----- Comprueba duplicado por id. ------
    if (repoFarmacos.obtener(idText) != null) {
      JOptionPane.showMessageDialog(this,
        "El ID ya existe: " + idText,
        "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
    }

    // -- Construye lista de dosificaciones (también para el Farmaco). --
    ArrayList<String> dosList = new ArrayList<>();
    for (String d : dosisText.split(",")) {
      dosList.add(d.trim());
    }

    // ------- Construye las Presentaciones. ----------
    ArrayList<Presentacion> presList = new ArrayList<>();
    for (String tipo : presText.split(",")) {
      Presentacion p = new Presentacion();
      p.setTipo(tipo.trim());
      p.setUnidad(unidad);
      p.setDosificaciones(new ArrayList<>(dosList));
      p.setPrecioUnidad(precio);
      presList.add(p);
    }

    // --- Farmaco completo. ---
    Farmaco farm = new Farmaco();
    farm.setIdFarmaco(id);
    farm.setNombre(nombre);
    farm.setValorFarmaco(precio);        
    farm.setDosificaciones(dosList);     
    farm.setPresentaciones(presList);

    // -- Agregar y refrescar. --
    repoFarmacos.agregar(farm);
    JOptionPane.showMessageDialog(this, "Fármaco agregado con éxito.");
    limpiarCamposYRefrescar();

  } catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "ID o precio inválido.");
  }
    }//GEN-LAST:event_jButtonAgregarFarmacoActionPerformed

    private void jButtonEliminarFarmacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarFarmacoActionPerformed
        int sel = jComboBoxEliminarFarmaco.getSelectedIndex();
        if (sel < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un fármaco.");
            return;
        }
        Farmaco f = listaFarmacosGestion.get(sel);
        repoFarmacos.eliminar(String.valueOf(f.getIdFarmaco()));
        JOptionPane.showMessageDialog(this, "Fármaco “" + f.getNombre() + "” eliminado.");
        limpiarCamposYRefrescar();
    }//GEN-LAST:event_jButtonEliminarFarmacoActionPerformed

    private void jComboBoxEliminarFarmacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEliminarFarmacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEliminarFarmacoActionPerformed

    private void jTPrecioUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrecioUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPrecioUnidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGestionarFarmaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGestionarFarmaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGestionarFarmaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGestionarFarmaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGestionarFarmaco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregarFarmaco;
    private javax.swing.JButton jButtonEliminarFarmaco;
    private javax.swing.JComboBox<String> jComboBoxEliminarFarmaco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTDosificacionesNuevas;
    private javax.swing.JTextField jTIdNuevoFarmaco;
    private javax.swing.JTextField jTNuevoFarmaco;
    private javax.swing.JTextField jTPrecioUnidad;
    private javax.swing.JTextField jTPresentacionesNuevas;
    private javax.swing.JTextField jTUnidadNuevoFarmaco;
    // End of variables declaration//GEN-END:variables
}
