package View;

import Controller.*;
import Model.*;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isaacmgz
 */

public class GUIVenta extends javax.swing.JFrame {

    private List<Farmaco> listaFarmacos;
    private List<Venta> ventasEnFactura = new ArrayList<>();
    private GestionClientes gestorClientes = new GestionClientes();
    private Map<String, Cliente> clientesById = new HashMap<>();

    public GUIVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarFarmacos();
        cargarClientes();
        configurarListeners();
    }

    private void cargarFarmacos() {
        try {
            GestionFarmacos repo = new GestionFarmacos();
            listaFarmacos = repo.cargarTodos();     // <-- método de instancia
            jComboBoxFarmaco.removeAllItems();

            for (Farmaco f : listaFarmacos) {
                jComboBoxFarmaco.addItem(f.getNombre());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void cargarClientes() {
        try {
            List<Cliente> lista = gestorClientes.cargarTodos();
            for (Cliente c : lista) {
                clientesById.put(c.getIdCliente(), c);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private void configurarListeners() {
        jComboBoxFarmaco.addActionListener(e -> {
            int index = jComboBoxFarmaco.getSelectedIndex();
            if (index >= 0) {
                Farmaco f = listaFarmacos.get(index);
                jComboBoxPresentacion.removeAllItems();
                jComboBoxDosificacion.removeAllItems();
                for (Presentacion p : f.getPresentaciones()) {
                    jComboBoxPresentacion.addItem(p.getTipo());
                }
            }
        });

        jComboBoxPresentacion.addActionListener(e -> {
            int farmacoIndex = jComboBoxFarmaco.getSelectedIndex();
            int presIndex = jComboBoxPresentacion.getSelectedIndex();

            if (farmacoIndex >= 0 && presIndex >= 0) {
                Farmaco f = listaFarmacos.get(farmacoIndex);
                Presentacion p = f.getPresentaciones().get(presIndex);

                jComboBoxDosificacion.removeAllItems();
                for (String dosis : p.getDosificaciones()) {
                    jComboBoxDosificacion.addItem(dosis + " " + p.getUnidad());
                }
            }
        });

        jFieldID.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                String id = jFieldID.getText().trim();
                Cliente c = gestorClientes.obtener(id);
                if (c != null) {
                    jFieldCliente.setText(c.getNombreCliente());
                    jFieldEmail.setText(c.getEmailCliente());
                } else {
                    jFieldCliente.setText("");
                    jFieldEmail.setText("");
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxFarmaco = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPresentacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDosificacion = new javax.swing.JComboBox<>();
        jButtonAgregarFarmaco = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonVerFactura = new javax.swing.JToggleButton();
        jButtonEliminarFactura = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFieldCliente = new javax.swing.JTextField();
        jFieldID = new javax.swing.JTextField();
        jFieldEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTCantidadFar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 157, 231));
        jLabel1.setText("Modulo de Venta");

        jComboBoxFarmaco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFarmaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFarmacoActionPerformed(evt);
            }
        });

        jLabel2.setText("Farmaco");

        jLabel3.setText("Presentación:");

        jComboBoxPresentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPresentacionActionPerformed(evt);
            }
        });

        jLabel4.setText("Dosificación:");

        jComboBoxDosificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDosificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDosificacionActionPerformed(evt);
            }
        });

        jButtonAgregarFarmaco.setText("Agregar Farmaco");
        jButtonAgregarFarmaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFarmacoActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(78, 157, 231));

        jSeparator2.setForeground(new java.awt.Color(78, 157, 231));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fármaco", "Presentación", "Dosificación", "Cantidad", "Valor Fármaco", "Gravamen", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jButtonVerFactura.setText("Generar Factura");
        jButtonVerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerFacturaActionPerformed(evt);
            }
        });

        jButtonEliminarFactura.setText("Eliminar Factura");
        jButtonEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarFacturaActionPerformed(evt);
            }
        });

        jLabel5.setText("Cliente:");

        jLabel6.setText("ID:");

        jLabel7.setText("Email:");

        jFieldCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldClienteActionPerformed(evt);
            }
        });

        jFieldID.setText("CLI");
        jFieldID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFieldIDFocusLost(evt);
            }
        });

        jLabel8.setText("Cantidad:");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFieldID, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(jFieldCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(jFieldEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBoxFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTCantidadFar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonAgregarFarmaco)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBoxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabel4)
                                                .addGap(28, 28, 28)
                                                .addComponent(jComboBoxDosificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jLabel1)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButtonVerFactura)
                        .addGap(90, 90, 90)
                        .addComponent(jButtonEliminarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxFarmaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxDosificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTCantidadFar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgregarFarmaco))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVerFactura)
                            .addComponent(jButtonEliminarFactura))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarFarmacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFarmacoActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {

            String idVenta = "TEMP"; // Será remplazado al final
            LocalDate fechaVenta = LocalDate.now();

            // --- cliente ----------------
            String idCli = jFieldID.getText().trim();
            Cliente cliente = clientesById.get(idCli);
            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente válido");
                return;
            }

            // --- fármaco y presentación reales -------------
            int farmIndex = jComboBoxFarmaco.getSelectedIndex();
            Farmaco f = listaFarmacos.get(farmIndex);

            int presIndex = jComboBoxPresentacion.getSelectedIndex();
            Presentacion p = f.getPresentaciones().get(presIndex);

            // dosis y cálculos 
            String dosificacion = jComboBoxDosificacion.getSelectedItem().toString();
            int cantidad = Integer.parseInt(jTCantidadFar.getText().trim());
            double valorUnitario = p.getPrecioPorUnidad();
            double valorTotal = valorUnitario * cantidad;
            double gravamen = valorTotal * 0.19;

            // --- crea la venta con los objetos completos ---
            Venta venta = new Venta(
                    "TEMP", // luego lo reasignas
                    LocalDate.now(),
                    cliente, // aquí ya trae idCliente y email
                    f, // objeto Farmaco completo
                    p, // Presentacion completo
                    dosificacion,
                    cantidad,
                    valorTotal
            );
            ventasEnFactura.add(venta);

            // --- añade la fila a la tabla -------------------
            DefaultTableModel model_Ux = (DefaultTableModel) jTable1.getModel();
            DecimalFormat df = new DecimalFormat("#,##0.00 $");
            model.addRow(new Object[]{
                f.getNombre(),
                p.getTipo(),
                dosificacion,
                cantidad,
                df.format(valorUnitario),
                df.format(gravamen),
                df.format(valorTotal)
            });

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al agregar fármaco: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonAgregarFarmacoActionPerformed

    private static int contadorVentas = 1;

    private void jButtonVerFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerFacturaActionPerformed

        GestionFactura f = new GestionFactura();
        try {
            GestionVenta gv = new GestionVenta();
            int contador = 1;
            for (Venta venta : ventasEnFactura) {
                venta.setIdVenta("V" + contador++);
                gv.registrarVenta(venta);
            }

            JOptionPane.showMessageDialog(this, "Factura generada con éxito");

            Venta ultimaVenta = ventasEnFactura.get(ventasEnFactura.size() - 1);
            f.crearFactura(jTable1, ultimaVenta);

            // Abrir el PDF generado automáticamente
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            java.io.File pdfFile = new java.io.File("src/main/java/ArchivosPersistencia/factura_simple.pdf");
            if (pdfFile.exists() && desktop.isSupported(java.awt.Desktop.Action.OPEN)) {
                desktop.open(pdfFile);
            }

            // Limpieza de la UI
            ventasEnFactura.clear();
            jFieldID.setText("");
            jFieldCliente.setText("");
            jFieldEmail.setText("");
            jTCantidadFar.setText("");
            jComboBoxFarmaco.setSelectedIndex(-1);
            jComboBoxPresentacion.removeAllItems();
            jComboBoxDosificacion.removeAllItems();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al generar factura: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonVerFacturaActionPerformed

    private void jComboBoxFarmacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFarmacoActionPerformed

    }//GEN-LAST:event_jComboBoxFarmacoActionPerformed

    private void jComboBoxPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPresentacionActionPerformed

    }//GEN-LAST:event_jComboBoxPresentacionActionPerformed

    private void jComboBoxDosificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDosificacionActionPerformed

    }//GEN-LAST:event_jComboBoxDosificacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUIEmpresa empresaWin = new GUIEmpresa();
        empresaWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFieldIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFieldIDFocusLost

        String ID = jFieldID.getText().trim();
        if (!ID.isEmpty()) {
            GestionClientes gestor = new GestionClientes();
            Cliente cliente = gestor.obtener(ID);
            if (cliente != null) {
                jFieldCliente.setText(cliente.getNombreCliente());
                jFieldEmail.setText(cliente.getEmailCliente());
            } else {
                jFieldCliente.setText("");
                jFieldEmail.setText("");
                JOptionPane.showMessageDialog(null, "Cliente no registrado.");
            }
        }
    }//GEN-LAST:event_jFieldIDFocusLost

    private void jFieldClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldClienteActionPerformed

    private void jButtonEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarFacturaActionPerformed
        // Limpia la lista interna
        ventasEnFactura.clear();

        // Limpia todos los campos de la UI
        jFieldID.setText("");
        jFieldCliente.setText("");
        jFieldEmail.setText("");
        jTCantidadFar.setText("");

        // Resetea los ComboBox
        jComboBoxFarmaco.setSelectedIndex(-1);
        jComboBoxPresentacion.removeAllItems();
        jComboBoxDosificacion.removeAllItems();

        // Limpia la tabla
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButtonEliminarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jButtonAgregarFarmaco;
    private javax.swing.JToggleButton jButtonEliminarFactura;
    private javax.swing.JToggleButton jButtonVerFactura;
    private javax.swing.JComboBox<String> jComboBoxDosificacion;
    private javax.swing.JComboBox<String> jComboBoxFarmaco;
    private javax.swing.JComboBox<String> jComboBoxPresentacion;
    private javax.swing.JTextField jFieldCliente;
    private javax.swing.JTextField jFieldEmail;
    private javax.swing.JTextField jFieldID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTCantidadFar;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
